// <auto-generated />
using System;
using Eduardo_G_300999807.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eduardo_G_300999807.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190411182010_Fixture")]
    partial class Fixture
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eduardo_G_300999807.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("League");

                    b.Property<string>("Name");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.Fixture", b =>
                {
                    b.Property<int>("FixtureId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AwayClubId");

                    b.Property<int>("AwayScore");

                    b.Property<int?>("HomeClubId");

                    b.Property<int>("HomeScore");

                    b.Property<DateTime>("MatchTime");

                    b.HasKey("FixtureId");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int?>("ClubId");

                    b.Property<string>("Name");

                    b.Property<int>("Overall");

                    b.HasKey("PlayerId");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.TransferLog", b =>
                {
                    b.Property<int>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int?>("FromClubClubId");

                    b.Property<int?>("PlayerId");

                    b.Property<int?>("ToClubClubId");

                    b.HasKey("TransferId");

                    b.HasIndex("FromClubClubId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ToClubClubId");

                    b.ToTable("TransferLog");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.Fixture", b =>
                {
                    b.HasOne("Eduardo_G_300999807.Models.Club", "Away")
                        .WithMany()
                        .HasForeignKey("AwayClubId");

                    b.HasOne("Eduardo_G_300999807.Models.Club", "Home")
                        .WithMany()
                        .HasForeignKey("HomeClubId");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.Player", b =>
                {
                    b.HasOne("Eduardo_G_300999807.Models.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId");
                });

            modelBuilder.Entity("Eduardo_G_300999807.Models.TransferLog", b =>
                {
                    b.HasOne("Eduardo_G_300999807.Models.Club", "FromClub")
                        .WithMany()
                        .HasForeignKey("FromClubClubId");

                    b.HasOne("Eduardo_G_300999807.Models.Player")
                        .WithMany("TransferLog")
                        .HasForeignKey("PlayerId");

                    b.HasOne("Eduardo_G_300999807.Models.Club", "ToClub")
                        .WithMany()
                        .HasForeignKey("ToClubClubId");
                });
#pragma warning restore 612, 618
        }
    }
}
